apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: microservices-blog
build:
  local:
    push: false
  artifacts:
    - image: joshcausey/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: src/**/*.js
    - image: joshcausey/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: comments/**/*.js
    - image: joshcausey/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: event-bus/**/*.js
    - image: joshcausey/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: moderation/**/*.js
    - image: joshcausey/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: posts/**/*.js
    - image: joshcausey/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: ./query/**/*.js
manifests:
  rawYaml:
    - infra/k8s/client-depl.yaml
    - infra/k8s/comments-depl.yaml
    - infra/k8s/event-bus-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/moderation-depl.yaml
    - infra/k8s/posts-depl.yaml
    - infra/k8s/posts-srv.yaml
    - infra/k8s/posts.yaml.old
    - infra/k8s/query-depl.yaml
